package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveUserScore;
import org.java.behave.db.domain.BehaveUserScoreExample;

public interface BehaveUserScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    long countByExample(BehaveUserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveUserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int insert(BehaveUserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int insertSelective(BehaveUserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserScore selectOneByExample(BehaveUserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserScore selectOneByExampleSelective(@Param("example") BehaveUserScoreExample example, @Param("selective") BehaveUserScore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveUserScore> selectByExampleSelective(@Param("example") BehaveUserScoreExample example, @Param("selective") BehaveUserScore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    List<BehaveUserScore> selectByExample(BehaveUserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserScore selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveUserScore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    BehaveUserScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserScore selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveUserScore record, @Param("example") BehaveUserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveUserScore record, @Param("example") BehaveUserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveUserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveUserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveUserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_score
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}