package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveUserClass;
import org.java.behave.db.domain.BehaveUserClassExample;

public interface BehaveUserClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    long countByExample(BehaveUserClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveUserClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int insert(BehaveUserClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int insertSelective(BehaveUserClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserClass selectOneByExample(BehaveUserClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserClass selectOneByExampleSelective(@Param("example") BehaveUserClassExample example, @Param("selective") BehaveUserClass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveUserClass> selectByExampleSelective(@Param("example") BehaveUserClassExample example, @Param("selective") BehaveUserClass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    List<BehaveUserClass> selectByExample(BehaveUserClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserClass selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveUserClass.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    BehaveUserClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUserClass selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveUserClass record, @Param("example") BehaveUserClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveUserClass record, @Param("example") BehaveUserClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveUserClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveUserClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveUserClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user_class
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}