package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveRole;
import org.java.behave.db.domain.BehaveRoleExample;

public interface BehaveRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    long countByExample(BehaveRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int insert(BehaveRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int insertSelective(BehaveRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveRole selectOneByExample(BehaveRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveRole selectOneByExampleSelective(@Param("example") BehaveRoleExample example, @Param("selective") BehaveRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveRole> selectByExampleSelective(@Param("example") BehaveRoleExample example, @Param("selective") BehaveRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    List<BehaveRole> selectByExample(BehaveRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    BehaveRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveRole record, @Param("example") BehaveRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveRole record, @Param("example") BehaveRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}