package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveLog;
import org.java.behave.db.domain.BehaveLogExample;

public interface BehaveLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    long countByExample(BehaveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int insert(BehaveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int insertSelective(BehaveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveLog selectOneByExample(BehaveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveLog selectOneByExampleSelective(@Param("example") BehaveLogExample example, @Param("selective") BehaveLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveLog> selectByExampleSelective(@Param("example") BehaveLogExample example, @Param("selective") BehaveLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    List<BehaveLog> selectByExample(BehaveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    BehaveLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveLog record, @Param("example") BehaveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveLog record, @Param("example") BehaveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}