package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveStorage;
import org.java.behave.db.domain.BehaveStorageExample;

public interface BehaveStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    long countByExample(BehaveStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int insert(BehaveStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int insertSelective(BehaveStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveStorage selectOneByExample(BehaveStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveStorage selectOneByExampleSelective(@Param("example") BehaveStorageExample example, @Param("selective") BehaveStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveStorage> selectByExampleSelective(@Param("example") BehaveStorageExample example, @Param("selective") BehaveStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    List<BehaveStorage> selectByExample(BehaveStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    BehaveStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveStorage record, @Param("example") BehaveStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveStorage record, @Param("example") BehaveStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}