package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveSystem;
import org.java.behave.db.domain.BehaveSystemExample;

public interface BehaveSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    long countByExample(BehaveSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int insert(BehaveSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int insertSelective(BehaveSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveSystem selectOneByExample(BehaveSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveSystem selectOneByExampleSelective(@Param("example") BehaveSystemExample example, @Param("selective") BehaveSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveSystem> selectByExampleSelective(@Param("example") BehaveSystemExample example, @Param("selective") BehaveSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    List<BehaveSystem> selectByExample(BehaveSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    BehaveSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveSystem record, @Param("example") BehaveSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveSystem record, @Param("example") BehaveSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}