package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveScheduleValue;
import org.java.behave.db.domain.BehaveScheduleValueExample;

public interface BehaveScheduleValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    long countByExample(BehaveScheduleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveScheduleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int insert(BehaveScheduleValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int insertSelective(BehaveScheduleValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveScheduleValue selectOneByExample(BehaveScheduleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveScheduleValue selectOneByExampleSelective(@Param("example") BehaveScheduleValueExample example, @Param("selective") BehaveScheduleValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveScheduleValue> selectByExampleSelective(@Param("example") BehaveScheduleValueExample example, @Param("selective") BehaveScheduleValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    List<BehaveScheduleValue> selectByExample(BehaveScheduleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveScheduleValue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveScheduleValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    BehaveScheduleValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveScheduleValue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveScheduleValue record, @Param("example") BehaveScheduleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveScheduleValue record, @Param("example") BehaveScheduleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveScheduleValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveScheduleValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveScheduleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_schedule_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}