package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveAdmin;
import org.java.behave.db.domain.BehaveAdminExample;

public interface BehaveAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    long countByExample(BehaveAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int insert(BehaveAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int insertSelective(BehaveAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveAdmin selectOneByExample(BehaveAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveAdmin selectOneByExampleSelective(@Param("example") BehaveAdminExample example, @Param("selective") BehaveAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveAdmin> selectByExampleSelective(@Param("example") BehaveAdminExample example, @Param("selective") BehaveAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    List<BehaveAdmin> selectByExample(BehaveAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    BehaveAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveAdmin record, @Param("example") BehaveAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveAdmin record, @Param("example") BehaveAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}