package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveUser;
import org.java.behave.db.domain.BehaveUserExample;

public interface BehaveUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    long countByExample(BehaveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int insert(BehaveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int insertSelective(BehaveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUser selectOneByExample(BehaveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUser selectOneByExampleSelective(@Param("example") BehaveUserExample example, @Param("selective") BehaveUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveUser> selectByExampleSelective(@Param("example") BehaveUserExample example, @Param("selective") BehaveUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    List<BehaveUser> selectByExample(BehaveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    BehaveUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveUser record, @Param("example") BehaveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveUser record, @Param("example") BehaveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}