package org.java.behave.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.behave.db.domain.BehaveTeacherQuestion;
import org.java.behave.db.domain.BehaveTeacherQuestionExample;

public interface BehaveTeacherQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    long countByExample(BehaveTeacherQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int deleteByExample(BehaveTeacherQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int insert(BehaveTeacherQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int insertSelective(BehaveTeacherQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveTeacherQuestion selectOneByExample(BehaveTeacherQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveTeacherQuestion selectOneByExampleSelective(@Param("example") BehaveTeacherQuestionExample example, @Param("selective") BehaveTeacherQuestion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BehaveTeacherQuestion> selectByExampleSelective(@Param("example") BehaveTeacherQuestionExample example, @Param("selective") BehaveTeacherQuestion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    List<BehaveTeacherQuestion> selectByExample(BehaveTeacherQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveTeacherQuestion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BehaveTeacherQuestion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    BehaveTeacherQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BehaveTeacherQuestion selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BehaveTeacherQuestion record, @Param("example") BehaveTeacherQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BehaveTeacherQuestion record, @Param("example") BehaveTeacherQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BehaveTeacherQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BehaveTeacherQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BehaveTeacherQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behave_teacher_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}